src/ecommerce/products/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from ..products import views


urlpatterns = [
    url(r'^$', views.ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', views.ProductDetailSlugView.as_view(), name='details'),
]

src/ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib.auth.views import LogoutView
from .views import home_page, \
    about_page, contact_page

from ecommerce.accounts.views import login_page, register_page
from ecommerce.carts.views import cart_home

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', home_page, name='home'),
    url('about/$', about_page, name='about'),
    url('contact/$', contact_page, name='contact'),
    url('login/$', login_page, name='login'),
    url('logout/$', LogoutView.as_view(), name='logout'),
    url('register/$', register_page, name='register'),
    url('bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    path('products/', include(('ecommerce.products.urls', 'ecommerce.products'), namespace='product')),
    path('search/', include(('ecommerce.search.urls', 'ecommerce.search'), namespace='search')),
    path('cart/', include(('ecommerce.carts.urls', 'ecommerce.carts'), namespace='cart'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<!-- FontAwesome CSS -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

src/templates/base/js.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'about' as about_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'product:list' as product_list_url %}
{% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">
            <img src="http://getbootstrap.com/docs/4.3/assets/brand/bootstrap-solid.svg" width="30" height="30" alt="" class="d-inline-block align-top">
            {% if brand_name %}
                {{ brand_name }}
            {% else %}
                CFE eCommerce
            {% endif %}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == home_url %}active{% endif %}">
                    <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
                    <a class="nav-link" href="{{ contact_url }}">Contact</a>
                </li>
                <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
                    <a class="nav-link" href="{{ product_list_url }}">Products</a>
                </li>

                {% if request.user.is_authenticated %}
                    <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                        <a class="nav-link" href="{{ logout_url }}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item {% if request.path == register_url %}active{% endif %}">
                        <a class="nav-link" href="{{ register_url }}">Register</a>
                    </li>
                    <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                        <a class="nav-link" href="{{ login_url }}">Login</a>
                    </li>
                {% endif %}
                <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
                    <a class="nav-link" href="{{ cart_url }}"> {{ request.session.cart_items }} <i class="fas fa-shopping-cart"></i></a>
                </li>

                {#                    <li class="nav-item dropdown">#}
                {#                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
                {#                            Dropdown link#}
                {#                        </a>#}
                {#                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">#}
                {#                            <a class="dropdown-item" href="#">Action</a>#}
                {#                            <a class="dropdown-item" href="#">Another action</a>#}
                {#                            <a class="dropdown-item" href="#">Something else here</a>#}
                {#                        </div>#}
                {#                    </li>#}
            </ul>
            {% include 'search/snippets/search-form.html' %}
        </div>
    </div>
</nav>